openapi: '3.0.2'
info:
  title: Practice_GoLang
  version: '1.0'
servers:
  - url: https://localhost:9000/v1


components:
  schemas:
    employee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        department_id:
          type: integer

  responses:
    NotFoundError:
      description: リソースが見つからないエラー
      content:
        application/json:
          schema:
            type: object
            properties:
              message: 
                type: string
                example: 'ユーザが見つかりません'

paths:
  /employee/{id}:
    get:
      parameters:
        - schema:
            type: integer
            description: 従業員ID
          in: path
          name: id
          required: true
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  employee:
                    $ref: '#/components/schemas/employee'
        '404':
          $ref: '#/components/responses/NotFoundError'
