swagger: "2.0"
info:
  title: Practice Go Lang
  version: 0.1.0
consumes:
- application/json
produces:
- application/json
schemes:
- http

paths:
  /employee/{id}:
    get:
      parameters:
        - in: path
          name: id
          type: string
          required: true
      responses:
        200:
          description: "OK"
          schema:
            type: object
            properties:
              employee:
                $ref: "#/definitions/employee"

definitions:
  employee:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      department_id:
        type: integer
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
    example:
      id: 1
      name: Kyohei Saito
      department_id: 1
      created_at: 2021-11-11T23:59:59
      updated_at: 2021-11-11T23:59:59

