// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Practice Go Lang",
    "version": "0.1.0"
  },
  "paths": {
    "/employee/{id}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "employee": {
                  "$ref": "#/definitions/employee"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "employee": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "department_id": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "example": {
        "created_at": "2021-11-11T23:59:59",
        "department_id": 1,
        "id": 1,
        "name": "Kyohei Saito",
        "updated_at": "2021-11-11T23:59:59"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Practice Go Lang",
    "version": "0.1.0"
  },
  "paths": {
    "/employee/{id}": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "employee": {
                  "$ref": "#/definitions/employee"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "employee": {
      "type": "object",
      "properties": {
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "department_id": {
          "type": "integer"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "example": {
        "created_at": "2021-11-11T23:59:59",
        "department_id": 1,
        "id": 1,
        "name": "Kyohei Saito",
        "updated_at": "2021-11-11T23:59:59"
      }
    }
  }
}`))
}
